packages:
  - apps/*
  - packages/*

catalogs: 
  public: #==========>Public catalog used for public part of monorepo
    eslint: 9.17.0
    "@types/node": 22.x
    glob: ^11.0.2
    consola: ^3.4.2
    "@sentry/node": ^8.26.0 
    "@sentry/profiling-node": ^8.26.0
    "joi": "17.13.3"
    ofetch: ^1.4.1
    "confbox": "0.1.8"
    #==============================> Static analysis
    tslib: 2.8.1
    typescript: ^5.7.2
    "unstorage": "^1.10.2"
    #==============================> Rollup
    "@rollup/plugin-commonjs": ^28.0.0
    "@rollup/plugin-json": ^6.1.0
    "@rollup/plugin-node-resolve": ^15.3.0
    "@rollup/plugin-terser": ^0.4.4
    "@rollup/plugin-typescript": ^12.1.1
    rollup: ^4.28.1